#!/bin/bash

# https://imapwiki.org/ImapTest/Installation

apt-get update
apt-get install -y curl file gcc libssl-dev make zlib1g-dev

cd /tmp
curl -OL http://dovecot.org/nightly/dovecot-latest.tar.gz
tar -C /tmp -xf dovecot-latest.tar.gz
dovesrc=$(echo /tmp/dovecot-0.0.0-*)
cd $dovesrc
./configure --without-shared-libs
make

cd /tmp
curl -OL http://dovecot.org/nightly/imaptest/imaptest-latest.tar.gz
tar -C /tmp -xf imaptest-latest.tar.gz
imaptestsrc=$(echo /tmp/dovecot-0.0-imaptest-*)
cd $imaptestsrc
./configure --with-dovecot=$dovesrc
make install
mkdir /usr/local/share/imaptest
cp -a src/tests /usr/local/share/imaptest

cd /usr/local/share/imaptest
curl -OL http://www.dovecot.org/tmp/dovecot-crlf

cd /tmp
rm -rf /tmp/dovecot* /tmp/imaptest-latest.tar.gz
